"""
Author: Sikder Tahsin Al Amin
Problem:
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t
Input:
s = "abcd"
t = "abcde"

Output:
e
"""
def findTheDifference(s,t):
    t_list=[]
    for i in t:
        t_list.append(i)
    for i in s:
        t_list.remove(i)
    return t_list[0]
